-- Seed the organization master list (healthcare sector).
--
-- Source: Healthcare_Organization_Master_List.xlsx (281 rows, 272 unique names).
-- Duplicate names in the sheet are collapsed here because organizations.name
-- carries a UNIQUE constraint; the sheet's "Category" column is intentionally
-- not imported, as the table has no category column.
--
-- Re-runnable: existing organizations are never duplicated, and a domain is
-- only filled in when the stored one is missing, so admin-entered values and
-- any manually corrected domains are preserved.

INSERT INTO public.organizations (name, domain, is_verified)
SELECT v.name, v.domain, true
FROM (VALUES
  ('Aragen Life Sciences', 'www.aragen.com'),
  ('Charles River Laboratories', 'www.criver.com'),
  ('Clario', 'clario.com'),
  ('Fortrea', 'www.fortrea.com'),
  ('GVK BIO', 'www.gvkbio.com'),
  ('ICON plc', 'www.iconplc.com'),
  ('IQVIA', 'www.iqvia.com'),
  ('Labcorp', 'www.labcorp.com'),
  ('Lambda Therapeutic Research', 'www.lambda-cro.com'),
  ('Medpace', 'www.medpace.com'),
  ('Novotech', 'novotech-cro.com'),
  ('PPD', 'www.ppd.com'),
  ('PSI CRO', 'psi-cro.com'),
  ('Parexel', 'www.parexel.com'),
  ('Premier Research', 'premier-research.com'),
  ('Siro Clinpharm', 'www.siroclinpharm.com'),
  ('Syneos Health', 'www.syneoshealth.com'),
  ('Syngene International', 'www.syngeneintl.com'),
  ('TFS HealthScience', 'www.tfshealthscience.com'),
  ('Thermo Fisher Scientific', 'www.thermofisher.com'),
  ('Veeda Clinical Research', 'www.veedacr.com'),
  ('Vimta Labs', 'vimta.com'),
  ('Abbott Diagnostics', 'www.corelaboratory.abbott'),
  ('Agilus Diagnostics', 'agilusdiagnostics.com'),
  ('Apollo Diagnostics', 'www.apollodiagnostics.in'),
  ('Beckman Coulter', 'www.beckmancoulter.com'),
  ('Danaher', 'www.danaher.com'),
  ('Dr. Lal PathLabs', 'www.lalpathlabs.com'),
  ('Illumina', 'www.illumina.com'),
  ('Metropolis Healthcare', 'www.metropolisindia.com'),
  ('Molbio Diagnostics', 'www.molbiodiagnostics.com'),
  ('Neuberg Diagnostics', 'www.neubergdiagnostics.com'),
  ('QIAGEN', 'www.qiagen.com'),
  ('Redcliffe Labs', 'redcliffelabs.com'),
  ('Roche Diagnostics', 'diagnostics.roche.com'),
  ('SRL Diagnostics', 'www.srl.in'),
  ('Siemens Healthineers', 'www.siemens-healthineers.com'),
  ('Strand Life Sciences', 'www.strandls.com'),
  ('Suburban Diagnostics', 'www.suburbandiagnostics.com'),
  ('Thyrocare', 'www.thyrocare.com'),
  ('Transasia Bio-Medicals', 'www.transasia.co.in'),
  ('Vijaya Diagnostic Centre', 'www.vijayadiagnostic.com'),
  ('Accenture', 'www.accenture.com'),
  ('Alvarez & Marsal', 'www.alvarezandmarsal.com'),
  ('Arthur D. Little', 'www.adlittle.com'),
  ('Avalere Health', 'avalerehealth.com'),
  ('Axtria', 'www.axtria.com'),
  ('Bain & Company', 'www.bain.com'),
  ('Boston Consulting Group (BCG)', 'www.bcg.com'),
  ('Clarivate', 'clarivate.com'),
  ('Deloitte', 'www.deloitte.com'),
  ('EVERSANA', 'www.eversana.com'),
  ('EY', 'www.ey.com'),
  ('EY-Parthenon', 'www.ey.com'),
  ('Fractal', 'fractal.ai'),
  ('Indegene', 'www.indegene.com'),
  ('KPMG', 'kpmg.com'),
  ('Kearney', 'www.kearney.com'),
  ('L.E.K. Consulting', 'www.lek.com'),
  ('McKinsey & Company', 'www.mckinsey.com'),
  ('Mu Sigma', 'www.mu-sigma.com'),
  ('Oliver Wyman', 'www.oliverwyman.com'),
  ('Putnam Associates', 'www.putassoc.com'),
  ('PwC', 'www.pwc.com'),
  ('Roland Berger', 'www.rolandberger.com'),
  ('Simon-Kucher', 'www.simon-kucher.com'),
  ('Strategy&', 'www.strategyand.pwc.com'),
  ('Tredence', 'www.tredence.com'),
  ('Trinity Life Sciences', 'www.trinitylifesciences.com'),
  ('ZS Associates', 'www.zs.com'),
  ('3one4 Capital', 'www.3one4capital.com'),
  ('A91 Partners', 'www.a91partners.com'),
  ('Accel', 'www.accel.com'),
  ('Advent International', 'www.adventinternational.com'),
  ('Bain Capital', 'www.baincapital.com'),
  ('Baring Private Equity Asia', 'www.bpeasia.com'),
  ('Blackstone', 'www.blackstone.com'),
  ('Blume Ventures', 'blume.vc'),
  ('Chiratae Ventures', 'www.chiratae.com'),
  ('ChrysCapital', 'www.chryscapital.com'),
  ('Eight Roads Ventures', 'www.eightroads.com'),
  ('Elevation Capital', 'www.elevationcapital.com'),
  ('Endiya Partners', 'www.endiyapartners.com'),
  ('Everstone Capital', 'www.everstonecapital.com'),
  ('Fireside Ventures', 'firesideventures.com'),
  ('General Atlantic', 'www.generalatlantic.com'),
  ('HealthQuad', 'healthquad.com'),
  ('India Value Fund Advisors', 'www.ivfa.com'),
  ('KKR', 'www.kkr.com'),
  ('Lightbox', 'www.lightbox.vc'),
  ('Multiples Alternate Asset Management', 'www.multiplesequity.com'),
  ('Nexus Venture Partners', 'nexusvp.com'),
  ('Peak XV Partners', 'www.peakxv.com'),
  ('TPG', 'www.tpg.com'),
  ('Temasek', 'www.temasek.com.sg'),
  ('The Carlyle Group', 'www.carlyle.com'),
  ('True North', 'www.truenorth.co.in'),
  ('Warburg Pincus', 'warburgpincus.com'),
  ('Apollo Hospitals', 'www.apollohospitals.com'),
  ('Artemis Hospitals', 'www.artemishospitals.com'),
  ('Aster DM Healthcare', 'www.asterdmhealthcare.com'),
  ('Breach Candy Hospital', 'www.breachcandyhospital.org'),
  ('CARE Hospitals', 'www.carehospitals.com'),
  ('Cloudnine Group of Hospitals', 'www.cloudninecare.com'),
  ('Fortis Healthcare', 'www.fortishealthcare.com'),
  ('HCG Cancer Centre', 'www.hcgoncology.com'),
  ('Hinduja Hospitals', 'www.hindujahospital.com'),
  ('Jaslok Hospital', 'www.jaslokhospital.net'),
  ('KIMS Hospitals', 'www.kimshospitals.com'),
  ('Kokilaben Dhirubhai Ambani Hospital', 'www.kokilabenhospital.com'),
  ('Lilavati Hospital and Research Centre', 'www.lilavatihospital.com'),
  ('MGM Healthcare', 'www.mgmhealthcare.in'),
  ('Manipal Hospitals', 'www.manipalhospitals.com'),
  ('Max Healthcare', 'www.maxhealthcare.in'),
  ('Medanta', 'www.medanta.org'),
  ('Nanavati Max Hospital', 'www.nanavatimaxhospital.org'),
  ('Narayana Health', 'www.narayanahealth.org'),
  ('Rainbow Children''s Hospital', 'www.rainbowhospitals.in'),
  ('Sahyadri Hospitals', 'www.sahyadrihospital.com'),
  ('Sir H. N. Reliance Foundation Hospital', 'www.rfhospital.org'),
  ('Wockhardt Hospitals', 'www.wockhardthospitals.com'),
  ('Yashoda Hospitals', 'www.yashodahospitals.com'),
  ('5C Network', 'www.5cnetwork.com'),
  ('API Holdings (PharmEasy)', 'pharmeasy.in'),
  ('Apollo 24/7', 'www.apollo247.com'),
  ('BeatO', 'www.beatoapp.com'),
  ('Cure.fit', 'www.cure.fit'),
  ('Dozee', 'www.dozee.health'),
  ('Eka Care', 'www.eka.care'),
  ('Even Healthcare', 'www.even.in'),
  ('GOQii', 'goqii.com'),
  ('HealthPlix', 'www.healthplix.com'),
  ('HealthifyMe', 'www.healthifyme.com'),
  ('Innovaccer', 'innovaccer.com'),
  ('Loop Health', 'loophealth.com'),
  ('Medi Assist', 'mediassist.in'),
  ('MediBuddy', 'www.medibuddy.in'),
  ('Netmeds', 'www.netmeds.com'),
  ('Niramai', 'www.niramai.com'),
  ('Plum', 'www.plumhq.com'),
  ('Portea', 'www.portea.com'),
  ('Practo', 'www.practo.com'),
  ('Qure.ai', 'qure.ai'),
  ('SigTuple', 'sigtuple.com'),
  ('Tata 1mg', 'www.1mg.com'),
  ('Tricog Health', 'tricog.com'),
  ('Ultrahuman', 'www.ultrahuman.com'),
  ('Visit Health', 'www.visithealth.com'),
  ('mfine', 'www.mfine.co'),
  ('Abbott', 'www.abbott.com'),
  ('Agappe Diagnostics', 'www.agappe.com'),
  ('Alcon', 'www.alcon.com'),
  ('Axio Biosolutions', 'www.axiobio.com'),
  ('B. Braun', 'www.bbraun.com'),
  ('BPL Medical Technologies', 'www.bplmedicaltechnologies.com'),
  ('Baxter', 'www.baxter.com'),
  ('Becton Dickinson (BD)', 'www.bd.com'),
  ('Bio-Rad Laboratories', 'www.bio-rad.com'),
  ('Boston Scientific', 'www.bostonscientific.com'),
  ('Cochlear', 'www.cochlear.com'),
  ('Dexcom', 'www.dexcom.com'),
  ('Dräger', 'www.draeger.com'),
  ('Edwards Lifesciences', 'www.edwards.com'),
  ('Forus Health', 'www.forushealth.com'),
  ('Fresenius Medical Care', 'www.freseniusmedicalcare.com'),
  ('GE HealthCare', 'www.gehealthcare.com'),
  ('Getinge', 'www.getinge.com'),
  ('HLL Lifecare', 'www.lifecarehll.com'),
  ('Healthium Medtech', 'www.healthium.com'),
  ('Hindustan Syringes & Medical Devices', 'www.hmdhealthcare.com'),
  ('Hologic', 'www.hologic.com'),
  ('Insulet', 'www.insulet.com'),
  ('Intuitive Surgical', 'www.intuitive.com'),
  ('J Mitra & Co', 'www.jmitra.co.in'),
  ('Johnson & Johnson MedTech', 'www.jnjmedtech.com'),
  ('Karl Storz', 'www.karlstorz.com'),
  ('Masimo', 'www.masimo.com'),
  ('Medtronic', 'www.medtronic.com'),
  ('Meril Life Sciences', 'www.merillife.com'),
  ('Mindray', 'www.mindray.com'),
  ('Nipro', 'www.nipro-group.com'),
  ('Olympus', 'www.olympus-global.com'),
  ('Perfint Healthcare', 'www.perfinthealthcare.com'),
  ('Philips', 'www.philips.com'),
  ('Poly Medicure', 'www.polymedicure.com'),
  ('ResMed', 'www.resmed.com'),
  ('Romsons', 'www.romsons.com'),
  ('Sahajanand Medical Technologies', 'www.sahajanandmedical.com'),
  ('Skanray Technologies', 'www.skanray.com'),
  ('Smith+Nephew', 'www.smith-nephew.com'),
  ('Stryker', 'www.stryker.com'),
  ('Terumo', 'www.terumo.com'),
  ('Trivitron Healthcare', 'www.trivitron.com'),
  ('Wipro GE Healthcare', 'www.gehealthcare.in'),
  ('Zimmer Biomet', 'www.zimmerbiomet.com'),
  ('AbbVie', 'www.abbvie.com'),
  ('Ajanta Pharma', 'www.ajantapharma.com'),
  ('Akums Drugs & Pharmaceuticals', 'www.akums.in'),
  ('Alembic Pharmaceuticals', 'alembicpharmaceuticals.com'),
  ('Alkem Laboratories Ltd.', 'www.alkemlabs.com'),
  ('Amgen', 'www.amgen.com'),
  ('Amneal Pharmaceuticals', 'www.amneal.com'),
  ('Aristo Pharmaceuticals', 'www.aristopharma.co.in'),
  ('Astellas Pharma', 'www.astellas.com'),
  ('AstraZeneca', 'www.astrazeneca.com'),
  ('Aurobindo Pharma', 'www.aurobindo.com'),
  ('Bausch Health', 'www.bauschhealth.com'),
  ('Bayer', 'www.bayer.com'),
  ('Bharat Biotech', 'www.bharatbiotech.com'),
  ('Biocon', 'www.biocon.com'),
  ('Biological E', 'www.biologicale.com'),
  ('Blue Cross Laboratories', 'www.bluecrosslabs.com'),
  ('Boehringer Ingelheim', 'www.boehringer-ingelheim.com'),
  ('Bristol Myers Squibb', 'www.bms.com'),
  ('Cadila Pharmaceuticals', 'www.cadilapharma.com'),
  ('Centaur Pharmaceuticals', 'www.centaurpharma.com'),
  ('Cipla', 'www.cipla.com'),
  ('Corona Remedies', 'www.coronaremedies.com'),
  ('Daiichi Sankyo', 'www.daiichisankyo.com'),
  ('Divi''s Laboratories', 'www.divislabs.com'),
  ('Dr. Reddy''s Laboratories', 'www.drreddys.com'),
  ('Eisai', 'www.eisai.com'),
  ('Eli Lilly and Company', 'www.lilly.com'),
  ('Emcure Pharmaceuticals', 'www.emcure.com'),
  ('Eris Lifesciences', 'www.eris.co.in'),
  ('FDC', 'www.fdcindia.com'),
  ('Franco-Indian Pharmaceuticals', 'www.francoindian.com'),
  ('GSK', 'www.gsk.com'),
  ('Galderma', 'www.galderma.com'),
  ('Gland Pharma', 'glandpharma.com'),
  ('Glenmark Pharmaceuticals', 'glenmarkpharma.com'),
  ('Granules India', 'granulesindia.com'),
  ('Hetero', 'www.heterodrugs.com'),
  ('Indian Immunologicals', 'www.indimmune.com'),
  ('Intas Pharmaceuticals', 'www.intaspharma.com'),
  ('Ipca Laboratories', 'www.ipca.com'),
  ('JB Chemicals & Pharmaceuticals', 'www.jbcpl.com'),
  ('Johnson & Johnson', 'www.jnj.com'),
  ('Laurus Labs', 'www.lauruslabs.com'),
  ('Lincoln Pharmaceuticals', 'www.lincolnpharma.com'),
  ('Lupin', 'www.lupin.com'),
  ('MANKIND PHARMA LTD', 'www.mankindpharma.com'),
  ('MSD', 'www.msd.com'),
  ('MSN Laboratories', 'www.msnlabs.com'),
  ('Macleods Pharmaceuticals', 'www.macleodspharma.com'),
  ('Marksans Pharma', 'marksanspharma.com'),
  ('Merck', 'www.merck.com'),
  ('Micro Labs', 'microlabs.in'),
  ('Natco Pharma', 'www.natcopharma.com'),
  ('Novartis', 'www.novartis.com'),
  ('Novo Nordisk', 'www.novonordisk.com'),
  ('Organon', 'www.organon.com'),
  ('Panacea Biotec', 'www.panaceabiotec.com'),
  ('Pfizer', 'www.pfizer.com'),
  ('Piramal Pharma', 'www.piramalpharma.com'),
  ('RPG Life Sciences', 'www.rpglifesciences.com'),
  ('Roche', 'www.roche.com'),
  ('SUN PHARMA', 'sunpharma.com'),
  ('Sanofi', 'www.sanofi.com'),
  ('Serum Institute of India', 'www.seruminstitute.com'),
  ('Servier', 'www.servier.com'),
  ('Shilpa Medicare', 'www.vbshilpa.com'),
  ('Strides Pharma Science', 'strides.com'),
  ('Takeda', 'www.takeda.com'),
  ('Teva Pharmaceuticals', 'www.tevausa.com'),
  ('Torrent Pharmaceuticals', 'www.torrentpharma.com'),
  ('UCB', 'www.ucb.com'),
  ('USV', 'www.usvindia.com'),
  ('Unichem Laboratories', 'www.unichemlabs.com'),
  ('Viatris', 'www.viatris.com'),
  ('Wockhardt', 'www.wockhardt.com'),
  ('Zydus Lifesciences', 'www.zyduslife.com')
) AS v(name, domain)
ON CONFLICT (name) DO UPDATE
SET
  domain = COALESCE(NULLIF(organizations.domain, ''), EXCLUDED.domain),
  is_verified = true,
  updated_at = now();

-- ---------------------------------------------------------------- VERIFY
-- Run after the INSERT. Expected: 296 total (27 pre-existing + 269 new),
-- 272 verified, and the three previously-NULL domains now filled in.
SELECT
  count(*)                                              AS total_orgs,
  count(*) FILTER (WHERE is_verified)                   AS verified,
  count(*) FILTER (WHERE domain IS NULL OR domain = '') AS missing_domain
FROM public.organizations;

SELECT name, domain, is_verified
FROM public.organizations
WHERE name IN ('ZS Associates', 'Novartis', 'SUN PHARMA')
ORDER BY name;
